name: generate-doc
run-name: Generate documentation
on: [push]
jobs:
  generate-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate documentation
        run: nimble doc uing.nim
        