name: run-tests
run-name: Run uing tests on macOS, Ubuntu, and Windows
on: [push]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: knicknic/os-specific-run@v1
        with:
          linux: sudo apt-get install -y libgtk-3-dev

      - name: Run tests for ${{ matrix.os }}
        run: | 
          >git clone https://github.com/neroist/libui-ng.git uing/libui
          nimble test
        