name: run-tests
run-name: Run uing tests on macOS, Ubuntu, and Windows
on: [push]
jobs:
  run-tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: stable
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - if: runner.os == 'windows-latest'
        name: Install gtk3 on Linux
        run: sudo apt-get install -y libgtk-3-dev
      - name: Run tests for ${{ matrix.os }}
        run: nimble test
        